chains:
  ethereum:
    name: Ethereum
    chainId: 1
    network: mainnet
    rpcUrls:
      - "https://rpc.ankr.com/eth"
    symbol: eth
  solana:
    name: Solana
    chainId: 101
    network: mainnet
    rpcUrls:
      - "https://solana-mainnet.g.alchemy.com/v2/e2usEg1LZtfVj5LRn2ksilanYfC27EVo"
    symbol: sol
  avax:
    name: Avalanche
    chainId: 43114
    network: mainnet
    rpcUrls:
      - "https://api.avax.network/ext/bc/C/rpc"
    symbol: avax
  bnb:
    name: Bnb
    chainId: 56
    network: mainnet
    rpcUrls:
      - "https://data-seed-prebsc-1-s1.binance.org:8545"
    symbol: bnb